### ISSUE TITLE
spec file multiple init_motor_names 

### ISSUE THREAD

**Issue by dschick** [dkriegner/xrayutilities#79] opened 2019-07-12 14:53 UTC
When using Sardana to generate SPEC files, the `init_motor_names `are written in every **scan header** and not once in the **file header**.
I know that this is not how the original SPEC definition looks like, but actually this allows to change the number of motors with using one SPEC file without chrashing e.g. PyMCA to show the scan headers.
However, when using xrayutilies, this results in a Warning
`XU.io.spec.SPECScan: Warning: incorrect number of initial motor positions`
since the `init_motor_names `are now a list of all occurences in the spec file so actually _n_ times the actual `init_motor_names`, where _n_ is the number of scans in the file.

There is already a workaround that reading the `init_motor_values `still works, but I was wondering if one could directly get rid of the warning.

My idea would be to move the `init_motor_names `from the SPEC_file to the SPEC_scan object.
Then one would has to check for the `init_motor_names `once in the file header and then in every scan header. But instead of concatenating, one would need to reset the `init_motor_names `list for every scan, if the `init_motor_names `are found again.

If you agree on this concept I would create a PR.

Best

Daniel

**Comment by dkriegner** [comment] 2019-07-14 21:21
If you manage to propose a change which does not break parsing of spec
files generated otherwise I am of course happy to merge a respective pull
request. Please consider my comments below which are of course up for
discussion.

I do not understand if Sardana writes init_mopo_names (#O) in the file
header or only in the scan header? Is a #O setting then valid for all the
further scans or only for the current scan? what if a scan does not have a
#O tag? does the global one from the file header apply or the one from the
last scan with a #O tag?

I think the most flexible (and maybe also easiest way to keep the behavior
for the "standard" spec files would be to keep the parsing of #O in
SPECFile. Since anyway already now the init_mopo_names are given as
parameter to the constructor of SPECScan one just have to implement a bit
more sophisticated logic in SPECFile and maybe remember the init_mopo from
the file header for the case when no local ones are given. otherwise the
local ones (or last parsed ones?) take preference.

**Comment by dschick** [comment] 2019-07-15 06:41
hej @dkriegner ,

Thanks for your opinion.

I will try to create PR soon. I guess, Sardana or SPEC write the #O tag differently, but at the end, it is about the software reading the SPEC files, how the #O tag is interpreted. As I said, PyMCA can handle a global and per-scan #O tags.
So the PR would be about enabling xrayutilities the same functionalities.

> Since anyway already now the init_mopo_names are given as
> parameter to the constructor of SPECScan one just have to implement a bit
> more sophisticated logic in SPECFile and maybe remember the init_mopo from
> the file header for the case when no local ones are given. otherwise the
> local ones (or last parsed ones?) take preference.

I had exactly the same way to go in mind.

**Comment by dkriegner** [comment] 2019-07-15 07:11
good, go ahead with the pull request.
Also I would appreciate a Sardana generated spec file to include in the
unit tests so that this keeps also working in future.

**Comment by dkriegner** [comment] 2019-07-19 10:04
@dschick: since the pull request is now merged, would you be willing to also supply a sardana generated spec file which needs this new features? I would write some basic unit tests around it to make it more likely that future changes won't break this feature

I would keep this issue open until the unit tests are committed

**Comment by dschick** [comment] 2019-07-19 17:22
where are the test io files are actually located?
Here you get a [demo SPEC file](https://gist.github.com/dschick/bf05b4bc905923f0ed9395420aaa5573#file-test_sardana2-8-spec) including changing number of init_motors, NANs in the data as well as an aborted scan as created by Sardana version 2.8.

**Comment by dkriegner** [comment] 2019-07-22 08:47
@dschick: I added a rather stupid unittest script to check the specific features of this data file. Although very basic these tests often helped me to avoid regression bugs. I consider this issue fixed. Let me know if you think otherwise.

The testfiles are so far only downloadable from sourceforge in a tarball:
https://sourceforge.net/projects/xrayutilities/files/
I added a readme in the test folder to make this more clear. 

If you agree I add your specfile there. This tarball is also loaded to Travis CI for automated testing upon every commit/pull request to this repository. Since this test data files rarely change and are slightly bigger I never considered a repository for these data.

**Closed by dkriegner** 2019-07-22 08:47 UTC

**Comment by dschick** [comment] 2019-07-22 11:26
sure, you can put the file there. I just thought of having the test data files also in the folder test. But I agree that it makes sense to store them separately .
The unit test looks okay for me.

Thanks for merging the PR!

**Comment by dkriegner** [comment] 2019-07-23 12:59
as a note after the fact: new test data are now available at [sourceforge](https://sourceforge.net/projects/xrayutilities/files/) and are also used (056c35200cb4669cb705a7164a3d4ef6710d2861) during tests on Travis-CI 

thanks for your contribution.
