### ISSUE TITLE
[Error] 1 error while running tests.

### ISSUE THREAD

**Issue by alexmarie78** [dkriegner/xrayutilities#89] opened 2019-10-23 08:30 UTC
Hello,

I am packaging python-xrayutilities for debian.
While I run the test, there is 69 skipped and 1 error.
I don't know why the test "test_materials_database.py" raises the error "Database creation error".

I checked in materials/_create_database.py but I didn't get how to pass this error.

Could you help me on here ?

Thanks in advance.

Alexandre Marie

**Comment by dkriegner** [comment] 2019-10-23 10:36
A few more details like the exact error message would of course be helpful! The error message you quote does not exist with that wording! Likely it was 'Database creation failed!'. Was there any other output than that?

Since the automated tests on travis-ci and app-veyor as well as on my local computer are working I expect that the problem comes somehow from the environment you use. Likely the problem is that the test wants to write a temporary file and might have problems with that?

For your information: The skipped tests are because you are missing the test data files needed to run all the tests. It depends on you but I think those are not needed for the packaging. details can be found here: 
https://github.com/dkriegner/xrayutilities/blob/master/tests/README.txt#L18

**Comment by alexmarie78** [comment] 2019-10-23 11:36
Thanks for your answer. 
My mistake, I forgot to give the error message. Here it is :

======================================================================
ERROR: setUpClass (tests.test_materials_database.TestDatabase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_xrayutilities/build/tests/test_materials_database.py", line 46, in setUpClass
    raise Exception('Database creation failed!')
Exception: Database creation failed!

----------------------------------------------------------------------


The error message is of course 'Database creation failed!'.

The issue comes when I build the package in a schroot. So the environment should be empty before the package is built. Thus I don't know why the test does not pass.
Still the error does not prevent the package from being built.

**Comment by dkriegner** [comment] 2019-10-23 12:35
ok, this output of course does not help much. my suspicion is that there is a problem with generating a temporary file within your schroot. This test is generating a temporary file which it needs to open for writing. There is however one other test which should have been run in your schroot which also uses such temporary files... 

I guess more debugging is needed.
can you replace the test by the updated [file](https://gist.github.com/dkriegner/e26b1e5213c5b72e506ba54ceb2939a5) which hopefully provides a more detailed error message, or otherwise give a detailed sequence of commands needed so that I can reproduce the schroot environment?

**Comment by alexmarie78** [comment] 2019-10-23 14:56
So I've tried with your file updated but it didn't produced what it was expected to.
Still I saw where the error come from, this is what I get : 

Traceback (most recent call last):

  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_xrayutilities/build/xrayutilities/materials/_create_database.py", line 70, in <module>
    add_mass_from_NIST(dbf, os.path.join(dataroot, 'nist_atom.dat'), verbose)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_xrayutilities/build/xrayutilities/materials/database.py", line 727, in add_mass_from_NIST
    with open(nistfile, "r") as nf:
FileNotFoundError: [Errno 2] No such file or directory: '/<<PKGBUILDDIR>>/.pybuild/cpython3_3.7_xrayutilities/build/tests/../xrayutilities/materials/data/nist_atom.dat'


I think this is the main issue.

**Comment by dkriegner** [comment] 2019-10-23 18:50
thats exactly what I expected. I did not expect the new test would fix the issue but at least we know where the problem is.

So what is the problem: The relevant files (and its more then the one which cause the error I guess) are missing from your schroot. In the sources there are several data files which are not installed by setup.py because the are in principle not needed at runtime. I guess you produce your schroot by some installation routine?

It seems that the unit tests when they are run in the source folder find these data files (see for example the [travis run for version 1.5.3](https://travis-ci.com/dkriegner/xrayutilities/jobs/244097353#L559).

I see two options to fix this also for your use case: 
1) Install all data files in the folder `xrayutilities/materials/data`. This can be achieved by a one line change in setup.py ([change here](https://github.com/dkriegner/xrayutilities/blob/master/setup.py#L150)). (You could also patch this somehow in the debian package for the moment if needed)

2) Disable that particular test if the needed source files are not found in the respective folder.

I guess solution 1) would be the better one. The only downside I see is that the distributed packages are getting a bit bigger. On the other hand one could maybe even think further and remove the pre-built database completely and let setuptools build it during the build phase. This would likely be quite elegant but is a bit more effort. 

So  for the moment if you need the tests to succeed I think you should patch setup.py or the respective schroot generation. For the setup.py solution this means a diff like this:

```
--- a/setup.py
+++ b/setup.py
@@ -146,10 +146,7 @@ setup(
     packages=find_packages(exclude=['tests']),
     package_data={
         "xrayutilities": ["*.conf"],
-        "xrayutilities.materials": [
-            os.path.join("data", "*.db"),
-            os.path.join("data", "*.cif")
-            ]
+        "xrayutilities.materials": [os.path.join("data", "*")]
         },
     data_files=[('xrayutilities', ['VERSION'])],
     install_requires=['numpy>=1.9.2', 'scipy>=0.11.0', 'h5py', 'setuptools'],
```

let me know what you think!

**Comment by alexmarie78** [comment] 2019-10-24 08:53
In order to build the package, I run the command : 

```
dgit sbuild
```

This command build the package in a schroot that should be clean.
I don't really know how this command access the schroot, but there is a buildDir created within the scrhoot and all files are created in it so there should be no problems..

In the debian rules file, here is the command ran for the tests : 

```
override_dh_auto_test:
	dh_auto_test -- -s custom --test-args="cp -r tests {build_dir}; {interpreter} {dir}/setup.py egg_info -e {build_dir}; cd {build_dir}; {interpreter} -m unittest2 discover -v; rm -rf {build_dir}/tests"
```

Hope it can help you

**Comment by alexmarie78** [comment] 2019-10-24 09:52
So I added args to the test to copy the data dir before the test and the remove it after.
It seems that now the test pass well. 
Here what have been added : 
```
 cp -r xrayutilities/materials/data {build_dir}/xrayutilities/materials/
 rm -rf {build_dir}/xrayutilities/materials/data
```

**Comment by dkriegner** [comment] 2019-10-24 11:27
Ok, good that you fixed it by this. I have to say I do not understand why these files were not already installed by sbuild. Of course I do not know exactly what this command does, but since it somehow will rely on setuptools I guess it should have installed these files.

For the next release I will change this particular test and include the database creation in the build process. This might solve this issue also (and likely create new ones :)). 

I suggest to close this issue and keep #90 as issue for the mentioned material database migration efforts.

**Closed** 2019-10-24 12:24 UTC
