### ISSUE TITLE
Typo in wyckpos.py

### ISSUE THREAD

**Issue by vespos** [dkriegner/xrayutilities#83] opened 2019-09-19 19:00 UTC
Hi,

I don't know if this issue has been raised already, but there is a typo in the file wyckpos.py for the space group 47 (Pmmm). The first wyckoff position is labelled as 8A instead of 8a, which raise an error when trying to build a crystal from a CIF file with that space group.

Best regards,
Vincent

**Comment by dkriegner** [comment] 2019-09-19 19:21
Dear Vincent,

I dont see the problem with this. The only thing which is somehow weird is
the ordering in the wyckpos.py file for this space group. It should start
with 1a. Note that space group 47 has more Wyckoff position than there are
letters in the alphabet. Therefore 8A is used after 4z. This is the same
when you look at the bilbao server for example. I should check what the
International tables use in this case.

But 8a could be confusing because the letter "a" would appear twice.

Regards
Dominik

**Comment by vespos** [comment] 2019-09-19 22:47
Thank you for the fast response! This makes sense. The error I am getting there is perhaps coming from regexp syntax when dealing with capital letter. When loading a CIF file with space group 47, I get the following error:
`invalid literal for int() with base 10: '8A'` in cif.py line 583: `wpn = [int(re.sub(r"([a-z])", r"", k)) for k in keys]` (line 583)
Shouldn't it be `wpn = [int(re.sub(r"([A-z])", r"", k)) for k in keys]` in order to account for the the capital letter in the wyckoff position?

Best wishes,
Vincent

**Comment by dkriegner** [comment] 2019-09-20 00:35
Ok I see. Your issue was fixed already in issue #81. When using the Git
master version it should not give this error. I will close this issue as
duplicate of #81

**Closed** 2019-09-20 07:16 UTC
