### ISSUE TITLE
Multiple call leads to "Resource temporarily unavailable"

### ISSUE THREAD

**Issue by pierre-eymeric** [dkriegner/xrayutilities#61] opened 2018-12-07 17:17 UTC
I run version 1.4.2 on a mac, in spyder from anaconda.
I have to run several time the following script: 

```
import xrayutilities as xu
import matplotlib.pyplot as plt

tt_max = 105
cryst_size = 4e-3

# Position in Pbam
pPb1 = (0.70828, 0.12368)  # (x,y,0.0)
pPb2 = (0.70822, 0.12778)  # (x,y,0.5)
pZr =  (0.24265, 0.12418, 0.24600)  # (x,y,z)
pO1 =  (0.27179, 0.15480)  # (x,y,0)
pO2 =  (0.29624, 0.09861)  # (x,y,0.5)
pO3 =  (0.03017, 0.26039, 0.27680)  # (x,y,z)
pO4 =  (0.20376)  # (0,0.5,z)
pO5 =  (0.22961)  # (0,0,z)

# Displacements
dx1, dy1 = 0.2, 0
qPb1 = (0.70828+dx1, 0.12368+dy1)
dx2, dy2 = -0.2, 0
qPb2 = (0.70822+dx2, 0.12778+dy2)
dx3, dy3, dz3 = 0.2, 0.2 , 0
qZr = (0.24265+dx3, 0.12418+dy3, 0.24600+dz3)

def inter(init, final, x):
    """ calculate intermediate positions from intial (i), (f) positions
    using interm = f + (o-f)*x with 0<=x<=1
    x=0 : interm = final
    x=1 : interm = original
    """
    return tuple([final[i] + (init[i]-final[i])*x for i in range(len(init))])

def calc_int(hpc,kpc,lpc):
    """return the intensity of the (hkl)_pc for a given x
    ---------------
    Indices corrrespondance:
        h_o = h_pc + k_pc
        k_o = -2h_pc + 2k+pc
        l_o = 2l_pc
    """
    PZO_powder = xu.simpack.Powder(PZO, 1, crystallite_size_gauss=cryst_size)
    pd = xu.simpack.PowderDiffraction(PZO_powder, tt_cutoff=tt_max)
    return pd.data[(hpc+kpc,-2*hpc+2*kpc,2*lpc)]['r']

intensity   = []
deplacement = []

for fx in range(0,11,1):
    x = fx/10.0
    xPb1 = inter(pPb1, qPb1, x)   #shift along [u,v,0]
    xPb2 = inter(pPb2, qPb2, x)   #shift along [u,v,0]
    xZr = inter(pZr, qZr, x)      #shift along [u,v,w]
    PZO = xu.materials.Crystal(
            "PZO", xu.materials.SGLattice(55, 5.878, 11.7829, 8.22750,
                                          atoms=[xu.materials.elements.Pb,
                                                 xu.materials.elements.Pb,
                                                 xu.materials.elements.Zr,
                                                 xu.materials.elements.O,
                                                 xu.materials.elements.O,
                                                 xu.materials.elements.O,
                                                 xu.materials.elements.O,
                                                 xu.materials.elements.O],
                                          pos=[('4g', xPb1),
                                          ('4h', xPb2),
                                          ('8i', xZr),
                                          ('4g', pO1),
                                          ('4h', pO2),
                                          ('8i', pO3),
                                          ('4f', pO4),
                                          ('4e', pO5)],
                                          occ=[0.5,0.5,1,0.5,0.5,1,0.5,0.5]))
    deplacement+=[x]
    intensity+=[calc_int(-2,-2,-3)]

print('Intensities vs x = ', intensity)
plt.figure()
ax = plt.subplot(111)
plt.xlabel(r"from final to initial state")
plt.ylabel(r"Intensity")
plt.plot(deplacement, intensity, 'ko-', label='PZO')
```

and after a few times (usually 3, sometimes more), I get the following error :

```
runfile('/.../Test-XRayUtilities-MWE.py', wdir='/.../Python')
Traceback (most recent call last):

  File "<ipython-input-3-796ada8871aa>", line 1, in <module>
    runfile('/.../Test-XRayUtilities-MWE.py', wdir='/.../Python')

  File "/.../anaconda/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/.../anaconda/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/.../Python/Test-XRayUtilities-MWE.py", line 81, in <module>
    intensity+=[calc_int(-2,-2,-3)]

  File "/.../Python/Test-XRayUtilities-MWE.py", line 50, in calc_int
    pd = xu.simpack.PowderDiffraction(PZO_powder, tt_cutoff=tt_max)

  File "/.../anaconda/lib/python3.6/site-packages/xrayutilities/simpack/powder.py", line 1779, in __init__
    mg.start()

  File "/.../anaconda/lib/python3.6/multiprocessing/managers.py", line 513, in start
    self._process.start()

  File "/.../anaconda/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)

  File "/.../anaconda/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)

  File "/.../anaconda/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)

  File "/.../anaconda/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()

BlockingIOError: [Errno 35] Resource temporarily unavailable
```

I then have to restart the kernel. 
Is there anything I could do to avoid this ?

**Comment by dkriegner** [comment] 2018-12-08 08:41
I can not reproduce the particular error, but I think I see the problem. 
There seems to be some problem with resource cleanup which I did not notice before but becomes evident upon the extensive use of `PowderDiffraction` which in principle is not necessary in the way you do it. 

As a quick fix you could try to define only one `PowderDiffraction` object in your script and modify the parameters of the material afterwards. e.g.:

```
PZO_powder = xu.simpack.Powder(PZO, 1, crystallite_size_gauss=cryst_size)
pd = xu.simpack.PowderDiffraction(PZO_powder, tt_cutoff=tt_max)
# example of modification of the Pb position
pd.mat.at0_Pb_4g_0_pos=0.45
pd.update_powder_lines(tt_max)
```

But your script is of course a valid way to intend to use it. I need debug this!

ps: consider using proper formatting of your python code since now one can't copy & paste it

**Comment by pierre-eymeric** [comment] 2018-12-08 08:45
Dear Dominik
Thanks for the workaround.
Sorry for the bad formatting. I tried to copy paste within the "code" function of GitHub. Should I avoid using this environment and make a simple copy/paste ? Can I edit the post ? I am new to GitHub ...
Once again thank you very much for your support. 
Best regards

Le December 8, 2018 8:41:14 AM UTC, Dominik Kriegner <notifications@github.com> a écrit :
>I can not reproduce the particular error, but I think I see the
>problem. 
>There seems to be some problem with resource cleanup which I did not
>notice before but becomes evident upon the extensive use of
>`PowderDiffraction` which in principle is not necessary in the way you
>do it. 
>
>As a quick fix you could try to define only one `PowderDiffraction`
>object in your script and modify the parameters of the material
>afterwards. e.g.:
>
>```
>PZO_powder = xu.simpack.Powder(PZO, 1,
>crystallite_size_gauss=cryst_size)
>pd = xu.simpack.PowderDiffraction(PZO_powder, tt_cutoff=tt_max)
># example of modification of the Pb position
>pd.mat.at0_Pb_4g_0_pos=0.45
>pd.update_powder_lines(tt_max)
>```
>
>But your script is of course a valid way to intend to use it. I need
>debug this!
>
>ps: consider using proper formatting of your python code since now one
>can't copy & paste it
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dkriegner/xrayutilities/issues/61#issuecomment-445442968

-- 
Envoyé de mon téléphone portable. Veuillez excuser les éventuelles corrections automatiques indues.

Prof. Pierre-Eymeric Janolin
Enseignant-Chercheur / Professor
Laboratoire SPMS, UMR CNRS-CentraleSupélec
twitter: @AdvFerroics

**Comment by dkriegner** [comment] 2018-12-09 11:07
with the commit above the issue should be fixed! The problem was that some processes used for the powder pattern calculation, did not get cleaned up.
It, however, is important to note that the fix is not perfect (I am afraid there is no perfect fix).
Whenever the simulation capabilities of PowderDiffraction are used (now they have to be explicitly enabled by the `enable_simulation` keyword argument) the `close()` routine should be called when the PowderDiffraction instance is no longer needed.

Repeatedly initializing `PowderDiffraction` (with simulations enabled) without using `close()` will still use the zombie processes and likely cause the originally reported error!

The same is true for `PowderModel` which also got now a `close()` method. The documentation was updated accordingly.

**Closed by dkriegner** 2018-12-09 11:07 UTC
Labels: bug
