### ISSUE TITLE
Best way to update SGLattice ?

### ISSUE THREAD

**Issue by pierre-eymeric** [dkriegner/xrayutilities#63] opened 2019-01-07 15:57 UTC
Hi, 
Once again, thanks a lot for making this great tool available to the community. 

I am interested in calculating the change in intensity of some diffraction peaks as a function of an external parameter. This parameter changes the positions of atoms in the unit cell as well as the lattice parameters. The unit cell is described in the triclinic P1 space group and does not change. (Specifically: the intensity of super-structure peaks related to the oxygen octahedra rotations in a perovskite cell, the external parameter being the angle of rotation). 

To do so, I define a triclinic crystal through:
`ABO = xu.materials.Crystal(
        "ABO", xu.materials.SGLattice(1, a, b, c, 90, 90, 90,
                        atoms=[...], pos=[...], occ=[...]) 
`
then define a powder of this material through:
`ABO_powder = xu.simpack.Powder(ABO, 1, crystallite_size_gauss=cryst_size)`
and compute the powder diffraction pattern with
`pd = xu.simpack.PowderDiffraction(ABO_powder, tt_cutoff=tt_max`

As both the lattice parameters and the positions of the atoms change when the external parameter varies, I need to loop through these for each value of my external parameter. This takes quite some time and seems a bit 'brute force'.

The `pd.update_powder_lines(tt_max)` does take into account the new positions but apparently not the change in lattice parameters. 

Is there a more efficient way to carry out these calculations ? I am not quite sure what is the time and resource-heavy part of this loop so I don't quite know what is to be optimised here. 

What would change if I were to carry out the same calculations for a thin film ?

As a side note: what is the reason behind choosing negative rather than positive Miller indices (as seen in the output of `xu.simpack.PowderDiffraction()`) ?

**Comment by dkriegner** [comment] 2019-01-07 19:20
> As both the lattice parameters and the positions of the atoms change when the external parameter varies, I need to loop through these for each value of my external parameter. This takes quite some time and seems a bit 'brute force'.

True, always redefining the full material is overkill when only some parameters are changing. I outline below how with PowderDiffraction you can do it more effective, however, you have to update to the latest GIT version!

> 
> The pd.update_powder_lines(tt_max) does take into account the new positions but apparently not the change in lattice parameters.

This I do not understand. At least in the latest version both the change in lattice parameter and position influence the PowderDiffraction.data object. 

Here a minimal example
```
import xrayutilities as xu
m = xu.materials.Crystal('test', xu.materials.SGLattice(1, 4,4,4, 90,90,90, atoms=['dummy', 'dummy'], pos=[('1a', (0, 0, 0)), ('1a', (0.5,0.5,0.51))]))
pd = xu.simpack.PowderDiffraction(m)
print(pd)
pd.mat.a = 4.1
pd.mat.at1_dummy_1a_2_pos = 0.6
pd.update_powder_lines(180)
print(pd)
```
The first print gives (excerpt):
```
      h k l     |    tth    |    |Q|    |Int     |   Int (%)
   ---------------------------------------------------------------
      (1, 0, 0)    22.2061      1.571         0.00        0.03
      (1, 1, 0)    31.6072      2.221         0.14      100.00
      (1, 1, 1)    38.9686      2.721         0.00        0.04
```

While the second print statement shows a split peak due to the change of the lattice parameter and changed intensity due to the change of the atom positions (again an excerpt):

```
      h k l     |    tth    |    |Q|    |Int     |   Int (%)
   ---------------------------------------------------------------
      (0, 1, 0)    22.2061      1.571         0.00        5.15
      (1, 1, 0)    31.2143      2.195         0.09      100.00
      (0, 1, 1)    31.6072      2.221         0.04       46.23
      (1, 1, 1)    38.6418      2.699         0.01        6.29
```

> 
> Is there a more efficient way to carry out these calculations ? I am not quite sure what is the time and resource-heavy part of this loop so I don't quite know what is to be optimised here.

As outlined in my example you can loop after the definition of PowderDiffraction. so basically this means in the loop you only run `update_powder_lines()` and extract whatever you need. I hope this is fast enough. Some optimization might still be possible. I will look into this.

> 
> What would change if I were to carry out the same calculations for a thin film ?

What you understand under "a thin film"? epitaxial single crystalline material? Obviously it also depends on the measurement geometry. you can look into the [`coplanar_intensity` function](https://github.com/dkriegner/xrayutilities/blob/master/xrayutilities/analysis/misc.py#L121) which calculates the intensity for one particular case. For others I do not have convenience functions and you would need to start from the StructureFactor and calculate the other corrections (geometry, absorption, polarization,...) on your own.

> 
> As a side note: what is the reason behind choosing negative rather than positive Miller indices (as seen in the output of xu.simpack.PowderDiffraction()) ?

No reason. this was fixed already (07368535695f9cd75e3d71f52737abf95220c71c) and now should use more common positive hkl as you see from my output above.

**Comment by pierre-eymeric** [comment] 2019-01-07 22:57
Thanks a lot. However, after reinstalling xrayutilities from source (deleting all directories with older versions and reinstalling through `pip install --global-option="--without-openmp" xrayutilities` I have now version 1.5.1), I get the following error message, even for your minimum working example: 

> File "/Users/.../anaconda/lib/python3.6/site-packages/xrayutilities/simpack/powder.py", line 2306, in update_powder_lines
>    self.conv_handlers[self.next_proc].add_convolver(fp)
> AttributeError: 'PowderDiffraction' object has no attribute 'conv_handlers'

Would you have any clue as to why ?

**Comment by dkriegner** [comment] 2019-01-08 01:17
> > File "/Users/.../anaconda/lib/python3.6/site-packages/xrayutilities/simpack/powder.py", line 2306, in update_powder_lines
> > self.conv_handlers[self.next_proc].add_convolver(fp)
> > AttributeError: 'PowderDiffraction' object has no attribute 'conv_handlers'
> 
> Would you have any clue as to why ?

I got the same error with version 1.5.1 thats why i fixed it in commit f299fc725a45ca220dde449651faaa014154d9c7 which is not included in 1.5.1 
you need to install the latest [GIT version](https://github.com/dkriegner/xrayutilities/archive/master.zip). 
see [here](https://github.com/dkriegner/xrayutilities#installation-source) for instructions

**Comment by pierre-eymeric** [comment] 2019-01-09 16:57
Sorry for the belated response but I struggled a bit getting the GIT version under anaconda. Now that it is done, it works like a charm and is much faster: thank you vey much !

**Comment by dkriegner** [comment] 2019-01-09 20:50
From your comment it seems that the issue is solved.
I close the issue. if you would encounter related problems we can reopen it.

**Closed by dkriegner** 2019-01-09 20:50 UTC
